{% set name = "python-daemon" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-daemon-{{ version }}.tar.gz
  sha256: 6c57452372f7eaff40934a1c03ad1826bf5e793558e87fef49131e6464b4dae5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.0
    - setuptools >=62.4.0
    - docutils
    - pip
  run:
    - python >=3.0
    - setuptools >=62.4.0
    - lockfile >=0.10
    - docutils

test:
  imports:
    - daemon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pagure.io/python-daemon/
  summary: Library to implement a well-behaved Unix daemon process.
  dev_url: https://pagure.io/python-daemon/
  license: Apache-2.0 AND GPL-3.0
  license_file:
    - LICENSE.ASF-2
    - LICENSE.GPL-3
  dev_url: https://pagure.io/python-daemon/

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ocefpaf
    - xylar
