{% set version = "3.0.1" %}

package:
  name: python-daemon
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-daemon/python-daemon-{{ version }}.tar.gz
  sha256: 6c57452372f7eaff40934a1c03ad1826bf5e793558e87fef49131e6464b4dae5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - twine
  run:
    - python >=3.6
    - lockfile >=0.10
    - setuptools
    - docutils

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - daemon

about:
  home: https://pagure.io/python-daemon/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.ASF-2
  summary: Library to implement a well-behaved Unix daemon process.
  dev_url: https://pagure.io/python-daemon/

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - ocefpaf
